export const BlogData = [
	{
		id: 1,
		title: "Navigating Landlord/Tenant Disputes",
		date: "February 16, 2023",
		image: "blog-details-img-1",
		category:"Real Estate Disputes",
		content: "",
		tags:["Agreements","Legal Rights"],
	},
	{
		id: 2,
		title: "Fighting for Your Civil Rights",
		date: "February 16, 2023",
		image: "blog-details-img-2",
		category:"Employment Discrimination",
		content: "",
		tags:["Rights & Justice","Legal Rights"],
	},
	{
		id: 3,
		title: "Protecting Rights with Breach of Warranty",
		date: "February 16, 2023",
		image: "blog-details-img-3",
		category:"Consumer Protection",
		content: "",
		tags:["Rights & Justice", "Consumer Protection","Legal Rights"],
	},
	{
		id: 4,
		title: "Automobile Accidents and Your Right",
		date: "February 16, 2023",
		image: "blog-details-img-4",
		category:"Personal Injury",
		content: "",
		tags:["Legal Rights","Accidents","Personal Injury"],
	},
	{
		id: 5,
		title: "The Grief of Wrongful Death",
		date: "February 16, 2023",
		image: "blog-details-img-5",
		category:"Personal Injury",
		content: "",
		tags:["Compensation","Personal Injury"],
	},
	{
		id: 6,
		title: "Understanding Construction Accidents",
		date: "February 16, 2023",
		image: "blog-details-img-6",
		category:"Personal Injury",
		content: "",
		tags:["Accidents","Compensation","Personal Injury"],
	},
	{
		id: 7,
		title: "The Consequences of Wrongful Termination",
		date: "February 16, 2023",
		image: "blog-details-img-7",
		category:"Labor & Employment",
		content: "",
		tags:["Labor Law"],
	},
];

