export const caseData = [
	{
		id: 1,
		title: "Trademark Infringement",
		subtitle: "Intellectual Property",
		caseName: "Trademark Infringement",
		Time: "04 Months",
		Lawyer: "Bryan Howard",
		image: "cases-details-img-1",
	},
	{
		id: 2,
		title: "Patent Infringement",
		subtitle: "Intellectual Property",
		caseName: "Patent Infringement",
		Time: "05 Months",
		Lawyer: "Bryan Howard",
		image: "cases-details-img-2",
	},
	{
		id: 3,
		title: "Breach of Warranty",
		subtitle: "Consumer Protection",
		caseName: "Breach of Warranty",
		Time: "07 Months",
		Lawyer: "Christine Lee",
		image: "cases-details-img-3",
	},
	{
		id: 4,
		title: "False Advertising",
		subtitle: "Consumer Protection",
		caseName: "False Advertising",
		Time: "03 Months",
		Lawyer: "Christine Lee",
		image: "cases-details-img-4",
	},
	{
		id: 5,
		title: "Drug Possession",
		subtitle: "Criminal Defense",
		caseName: "Drug Possession",
		Time: "o4 Months",
		Lawyer: "Aubrey Nguyen",
		image: "cases-details-img-5",
	},
	{
		id: 6,
		title: "Fraud",
		subtitle: "Criminal Defense",
		caseName: "Fraud",
		Time: "05 Months",
		Lawyer: "Aubrey Nguyen",
		image: "cases-details-img-6",
	},
	{
		id: 7,
		title: "Defamation",
		subtitle: "Personal Injury",
		caseName: "Defamation",
		Time: "08 Months",
		Lawyer: "Neal Houston",
		image: "cases-details-img-7",
	},
	{
		id: 8,
		title: "Workplace Injury",
		subtitle: "Personal Injury",
		caseName: "Workplace Injury",
		Time: "06 Months",
		Lawyer: "Neal Houston",
		image: "cases-details-img-8",
	},
];
